#!/usr/bin/env bash
# bash script to create a ssh key pair

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -C "$KEY_NAME" -N "$PASSPHRASE" -f ~/.ssh/$KEY_NAME
